### ISSUE TITLE
Mailcatcher does not start

### ISSUE THREAD

**Issue by Antti** [tophfr/docker-mailcatcher#1]
After an update to `689e71096a1a`, a new version of docker-mailcatcher does not start, I receive this error:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher/mail.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:27:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.5/bin/mailcatcher:3:in `<top (required)>'
        from /usr/bin/mailcatcher:23:in `load'
        from /usr/bin/mailcatcher:23:in `<main>'
```

**Comment by mariusgrigaitis** [comment]
Got the same error.

**Comment by lcoq** [comment]
Got the same, need to use another `mailcatcher` image :(

**Comment by Eyjafjallajokull** [comment]
Until PR #2 merge you can use image tophfr/mailcatcher:0.5.12

**Comment by tophfr** [comment]
That's strange
I never experienced this issue from any builded images.
Last commit and image from docker hub is ok.
Thx
